### ISSUE TITLE
Make onsite filter out driving projects

### ISSUE THREAD

**Issue by santolucito** [newhaven-helpwithcovid/covid-volunteers#103]
on the homepage, we have three featured categories. Onsite and driving have overlap, so some projects are being displayed twice. We would like to change the onsite category selection so that it displays projects that are onsite and NOT driving. Alternatively, it might be easier to change the driving category selection to filter out onsite.

One line that might be good to check is :

https://github.com/newhaven-helpwithcovid/covid-volunteers/blob/1d309e5111af28321436a01f54f262371b034fc5/app/views/home/_project-category.html.erb#L10

**Comment by ltan3** [comment]
Note to self: change method `relevant_projects()` in home_controller.rb so that if the method is asked for onsite projects, it doesn't return projects that need driving. The featured categories themselves are defined in settings.yml.
