### ISSUE TITLE
Change language from "project" to "volunteer position"--applicable throughout website

### ISSUE THREAD

**Issue by tiffanywschan** [newhaven-helpwithcovid/covid-volunteers#16]

**Comment by chena11356** [comment]
In the navigation bar, the distinction between "Volunteered Projects" and "Your Projects" might be confusing if we change the wording -- should we leave that?

**Comment by chena11356** [comment]
And in some other places too, like when you're creating a new project.

**Comment by tiffanywschan** [comment]
I think as long as it’s very clear that our website is about volunteer positions, not projects. We are recruiting for a specific position, people are applying for specific positions. Having the word projects would be confusing.

**Comment by tiffanywschan** [comment]
It’s okay to keep it as “filter by project type” on landing page though.

**Comment by chena11356** [comment]
Got it! There's actually a bunch of places where it seems like "volunteer positions" might be clunky so I'll leave it in a couple places and if there's still some that you think should be changed just let me know.

**Comment by tiffanywschan** [comment]
Great. Thanks!

---
Tiffany Chan
M.A. Candidate
Yale University | Jackson Institute for Global Affairs
