### ISSUE TITLE
Affiliation for volunteers should be a drop down menu

### ISSUE THREAD

**Issue by tiffanywschan** [newhaven-helpwithcovid/covid-volunteers#21]

**Comment by whonore** [comment]
What should the list of options be?

**Comment by tiffanywschan** [comment]
Let’s make it a space for them to fill it in themselves, so

Institutional Affiliation: ________

**Comment by whonore** [comment]
So just a text field, not a drop-down?

**Comment by tiffanywschan** [comment]
Yes.
