### ISSUE TITLE
New skills list

### ISSUE THREAD

**Issue by tiffanywschan** [newhaven-helpwithcovid/covid-volunteers#27]
Access to car
ArcGIS
Arts and crafts
BHL (biohazard level) lab certificate
Childcare
Communications
CPR certificate
Culinary skills and access to kitchen
Database architecture
Driver's license
Door-to-door canvassing
EPIC access
Grant writing
IRB experience
Spanish language
Languages other than English and Spanish
Logistics and supply chain management
Phlebotomy
Phone bank
Management experience
Software programming
Statistical analysis

**Comment by tiffanywschan** [comment]
Also add: 
Survey design
Interviewing/focus groups 
Data management
Web development

**Comment by santolucito** [comment]
Fixed with f3fc0fa346b3a960e009d5852b0e3268b6463b4f
