### ISSUE TITLE
Include a disclaimer

### ISSUE THREAD

**Issue by bd-d** [newhaven-helpwithcovid/covid-volunteers#3]
Add clear a disclaimer indicating that the website is an aggregator and that Yale/the Co New Haven and are not responsible for any content or its use.

It sounds as though Tiffany/Matt may be able to provide the exact wording and where it needs to be displayed.

**Comment by tiffanywschan** [comment]
"Disclaimer for New Haven Help with COVID
If you require any more information or have any questions about our site's disclaimer, please feel free to contact us by email at newhavenpandemic@gmail.com

Disclaimers for New Haven Help with COVID
All the information on this website - newhavenhelpwithcovid.com - is published in good faith and for general information purpose only. New Haven Help with COVID does not make any warranties about the completeness, reliability and accuracy of this information. Any action you take upon the information you find on this website (New Haven Help with COVID), is strictly at your own risk. New Haven Help with COVID will not be liable for any losses and/or damages in connection with the use of our website. 

From our website, you can visit other websites by following hyperlinks to such external sites. While we strive to provide only quality links to useful and ethical websites, we have no control over the content and nature of these sites. These links to other websites do not imply a recommendation for all the content found on these sites. Site owners and content may change without notice and may occur before we have the opportunity to remove a link which may have gone 'bad'.

Please be also aware that when you leave our website, other sites may have different privacy policies and terms which are beyond our control. Please be sure to check the Privacy Policies of these sites as well as their "Terms of Service" before engaging in any business or uploading any information.

Consent
By using our website, you hereby consent to our disclaimer and agree to its terms.

Update
Should we update, amend or make any changes to this document, those changes will be prominently posted here."
