### ISSUE TITLE
Edit volunteer position page

### ISSUE THREAD

**Issue by tiffanywschan** [newhaven-helpwithcovid/covid-volunteers#30]
1)Organization is not optional--it should be required, same for position name
2)Description of project should also be required
3)Remove urgency line
4) Is background screening required? Yes/No
5)Add a line "Level of exposure: I, II, III, IV, V" (drop menu) with some link or box that explains what those are
Here are the level of exposure guidelines: 
I – no risk – from home
M1, M2, M3, M4
Mask production at home*
Creating cards/posters/videos of encouragement
 
Call center staffing from home
Call center staffing if proper social distancing is guaranteed
Check in calls to particularly vulnerable patients and/or to staff who were exposed
 
II - low risk and minimal human contact 
M1, M2, M3, M4
 
III – potential for human contact
M1, M2, M3, M4
Child care needs of “mission-critical on-site” staff during COVID-19 outbreak
 
Meal preparation, distributing food, washing dishes
Essential transportation needs for family members
 
IV – non-clinical but in hospital or office setting
M1, M2, M3, M4
Staff support in non-clinical dept of hospital or office practice (eg, information desk)
Duties usually performed by hospital volunteers
 
V – clinical and direct human contact
M3 and M4
Thermal imaging of hospital or office entrants
H&P’s, IV’s, blood draws etc

**Comment by santolucito** [comment]
I did 1,2, and 3 with commit f5cf2492f1a91564423235a4e2bc4efbe9fbbc73, but still need to add new fields to the database. @sarimabbas can you take a shot?

**Comment by sarimabbas** [comment]
As per ActiveRecord docs: https://edgeguides.rubyonrails.org/active_record_migrations.html, the way to create a change to the DB schema is to use special rails commands:

```bash
rails g migration AddBackgroundScreeningRequiredToProject background_screening_required:boolean

rails db:migrate
```

The first command creates the migration. The second updates the model and the database. I'll work on getting the field visible in the frontend HTML now, and then i'll push the changes. The rest of the team might also have to run `rails db:migrate` after pulling

**Comment by sarimabbas** [comment]
@santolucito  

* Added number 4 in https://github.com/newhaven-helpwithcovid/covid-volunteers/tree/feature/volunteer-position-fields :  https://github.com/newhaven-helpwithcovid/covid-volunteers/commit/49db657158222be1812127836591b4be71b176ee.
* Added db functionality for 5 in https://github.com/newhaven-helpwithcovid/covid-volunteers/commit/91c6853483f24817c764b83b5d3f0a11ca41279a
* Added the information box to describe the exposure levels here: https://github.com/helpwithcovid/covid-volunteers/commit/8dae443884009bfe223f77236ff9814668c59ca6
* Might use a collapsible component which is visible when a "Explain" link is clicked in the future

**Comment by sarimabbas** [comment]
@joyceduan07 Here is an example of a db migration
