### ISSUE TITLE
Mailchimp (for managing newsletter) code for people to sign up for biweekly newsletter

### ISSUE THREAD

**Issue by tiffanywschan** [newhaven-helpwithcovid/covid-volunteers#37]
<script type="text/javascript" src="//downloads.mailchimp.com/js/signup-forms/popup/unique-methods/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">window.dojoRequire(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us19.list-manage.com","uuid":"78fae43357cca3320ed5fb821","lid":"97d3425a6c","uniqueMethods":true}) })</script>

**Comment by santolucito** [comment]
can you expand on what needs to happen here? just posting code is not enough for us to go on

**Comment by tiffanywschan** [comment]
Please link to landing page for MailChimp: https://mailchi.mp/88b5c8c73c61/nhhelpwithcovid

**Comment by tiffanywschan** [comment]
Please include Facebook and Twitter icons and newsletter sign up link in on the landing page in the New Haven Residents vs. COVID-19 box?
