### ISSUE TITLE
Update volunteer/applicant attributes

### ISSUE THREAD

**Issue by bd-d** [newhaven-helpwithcovid/covid-volunteers#4]
Update user profiles to align with Tiffany's specification.

I think this means adding:
- Phone
- Affiliation
- Availability (day/time - I imagine this should be integrated into the existing availability function)
- Resume

Per Tiffany's comment, she will also provide the relevant skills list to include.

**Comment by santolucito** [comment]
Phone, Affiliation and availability should be easy as they are just text fields. Resume is a pain if we want pdf uploads. Can we ask users to just add a link to a resume they posted elsewhere (e.g. personal website or google drive)?

**Comment by chena11356** [comment]
Should we also update the Location option? Since the city is, of course, going to be New Haven (or remote) -- maybe we can have dropdown options for different parts of the city, like East Rock, Yale Medical School campus, central new haven (near Old Campus), etc.? This might also make it easier to filter for volunteers by location. This would also need to be updated as a project attribute.

**Comment by santolucito** [comment]
Let's add a note to the location field that it should be in New Haven, but I still see a use case for location (eg homeless shelter, Yale-New Haven hospital, remote, etc)

**Comment by tiffanywschan** [comment]
Can see why PDF resume upload is a pain. Is it possible to encourage people to post links (linkedin, personal website, google drive), and those who can't to write short description or post text?

**Comment by tiffanywschan** [comment]
[Skills list for website.docx](https://github.com/newhaven-helpwithcovid/covid-volunteers/files/4398911/Skills.list.for.website.docx)

**Comment by tiffanywschan** [comment]
Note that I might add more to skills list later. But this is just to get us started.

**Comment by tiffanywschan** [comment]
Please add "clinical trials" under skills.

**Comment by tiffanywschan** [comment]
Please use this updated skills list instead: 
[Skills list for website.docx](https://github.com/newhaven-helpwithcovid/covid-volunteers/files/4399152/Skills.list.for.website.docx)

**Comment by chena11356** [comment]
I added all the skills except for the ones with a menu (languages) -- those might be easier to add as entirely new attributes.
