### ISSUE TITLE
Add to role (volunteer/recruiter) to users

### ISSUE THREAD

**Issue by tiffanywschan** [newhaven-helpwithcovid/covid-volunteers#40]
You are interested in: volunteering/recruiting (have to pick one option).

**Comment by santolucito** [comment]
in order to do this, we need to add a field to users. This requires a database migration to add the new field, updating the views of the user, and updating the view for signups

**Comment by santolucito** [comment]
@tiffanywschan is this still something we are interested in doing?

**Comment by santolucito** [comment]
since we haven't heard anything about this, closing for now - feel free to reopen if needed
