### ISSUE TITLE
[Urgent] Please add an asterisk next to level of exposure in job posting and have a link in the footer of website to a page about the levels of exposure

### ISSUE THREAD

**Issue by tiffanywschan** [newhaven-helpwithcovid/covid-volunteers#42]

**Comment by tiffanywschan** [comment]
Text: 

Guidelines
I: No risk/from home
M1, M2, M3, M4
Mask production at home
Creating cards/posters/videos of encouragement
Call center staffing from home
Call center staffing if proper social distancing is guaranteed
Check in calls to particularly vulnerable patients and/or to staff who were exposed

II: Low risk and minimal human contact
M1, M2, M3, M4

III: Potential for human contact
M1, M2, M3, M4
Child care needs of “mission-critical on-site” staff during COVID-19 outbreak
Meal preparation, distributing food, washing dishes
Essential transportation needs for family members

IV: Non-clinical but in hospital or office setting
M1, M2, M3, M4
Staff support in non-clinical dept of hospital or office practice (e.g. information desk)
Duties usually performed by hospital volunteers

V: Clinical and direct human contact
M3, M4
Thermal imaging of hospital or office entrants
H&P’s, IV’s, blood draws etc

**Comment by tiffanywschan** [comment]
Link in footer could be called "Risks".

**Comment by chena11356** [comment]
What do M1, M2, M3, and M4 represent? Should we include an explanation?

**Comment by tiffanywschan** [comment]
I don't know either...

**Comment by chena11356** [comment]
Haha okay, I guess we can just leave them in there for now?

**Comment by tiffanywschan** [comment]
Yes, let’s do that.
