### ISSUE TITLE
Give admin ability to delete volunteer profiles upon request

### ISSUE THREAD

**Issue by tiffanywschan** [newhaven-helpwithcovid/covid-volunteers#43]
Meanwhile, please delete the profile ****** ********. Thanks!

note: edited for privacy

**Comment by sarimabbas** [comment]
It seems like this ability should already exist, but I'll investigate further.

https://github.com/newhaven-helpwithcovid/covid-volunteers/blob/51a069c4ab95051869395a64ae3d37c3f436a08f/app/views/devise/registrations/show.html.erb#L13-L25

**Comment by tiffanywschan** [comment]
Thank you, Sarim!

**Comment by santolucito** [comment]
I have deleted this user. This ability does already exist for admin users (right now admins are @tiffanywschan and @santolucito). Just go to a user's profile, and there is a delete button. 

Also @tiffanywschan, please do not post ANY user information on here. These issues are public and can be seen by anyone.
