### ISSUE TITLE
[Urgent] Add a check box and line on volunteer profile page for signing up for newsletters

### ISSUE THREAD

**Issue by tiffanywschan** [newhaven-helpwithcovid/covid-volunteers#45]
Place it at the bottom of the page right before people save their volunteer profile:

A check box and a line that says "I'm interested in receiving regular email updates on the latest volunteering openings." 

Here's the mailchimp code to embed for sign up on the volunteer profile:

<script type="text/javascript" src="//downloads.mailchimp.com/js/signup-forms/popup/unique-methods/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">window.dojoRequire(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us19.list-manage.com","uuid":"78fae43357cca3320ed5fb821","lid":"97d3425a6c","uniqueMethods":true}) })</script>

**Comment by joyceduan** [comment]
Is the idea to have a pop up appear when the check box is clicked or to have them be automatically subscribed when they save?

**Comment by tiffanywschan** [comment]
The idea is to have a line there with a check box that they can check saying basically please sign me up for newsletters.

**Comment by chena11356** [comment]
It looks like the code provided by Mailchimp allows you to subscribe, but not in a checkbox format -- instead it looks like a button that opens a pop-up for you to type in your email, and then subscribe. It might take longer to reformat this into a checkbox (I'm not sure if Mailchimp offers that capability), so would this button popup suffice for now?

**Comment by tiffanywschan** [comment]
The button popup suffice for now. Thanks a lot!

**Comment by chena11356** [comment]
Actually my bad, so I read it wrong -- according to [this article](https://www.create.net/support/how-to-add-a-mailchimp-signup-form-to-your-website) , Mailchimp lets you export code as either an embedded sign-up form or a popup that only appears when you first visit the site. 

It looks like the former is more useful to us than the latter, so would it be possible for you to go into Mailchimp, change the settings, and get the embedded sign-up code rather than the popup code?

**Comment by tiffanywschan** [comment]
I’ve just sent you username and password for MailChimp in slack DM. I’m not sure how to change the settings so I think I should let you handle it. Thanks! The verification code is sent to our newhavenpandemic@gmail.com <mailto:newhavenpandemic@gmail.com>

**Comment by sarimabbas** [comment]
There are a bunch of tutorials that use Gibbon, which I'll investigate
- https://github.com/amro/gibbon
- https://medium.com/@afkehaya/how-to-us-the-gibbon-gem-with-devise-to-add-your-users-to-a-mail-chimp-list-when-they-signup-4b5dc56dcbdf

**Comment by chena11356** [comment]
Gibbon looks perfect! I've been trying to use the following Mailchimp code but it's not working with Rails (for some reason the subscribe button is acting like it's saving the profile instead, and not actually subscribing the email to anything). 


<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://newhavenhelpwithcovid.us19.list-manage.com/subscribe/post?u=78fae43357cca3320ed5fb821&amp;id=97d3425a6c" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address </label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_78fae43357cca3320ed5fb821_97d3425a6c" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

**Comment by sarimabbas** [comment]
Ahh I see! I tried the JS as well but didn't have any luck. I ended up integrating Gibbon and things work so far! In a few moments I'll push the branch. Would love to get your help cleaning up the code/good style etc

**Comment by sarimabbas** [comment]
Check out https://github.com/newhaven-helpwithcovid/covid-volunteers/pull/52 if you get the chance
