### ISSUE TITLE
Add Blank Slate integration

### ISSUE THREAD

**Issue by santolucito** [newhaven-helpwithcovid/covid-volunteers#53]
Add a status symbol on user profiles that indicates if they are up to date on training, according to Blank Slate. The plan is to integrate with the Blank Slate api to simply lookup user status by email. We should also add a link to blank slate next to this status so users can sign up.

Would be cool to send users to the blank slate log in page while passing a url param with their email that blank slate can use to fill in their log in/sign up form

**Comment by whonore** [comment]
How often should the app check if a user is up to date on training? On login, before volunteering for something, some fixed time window?

**Comment by santolucito** [comment]
I think we just call their API everytime a user profile is displayed and get the most up-to-date value at that time.

**Comment by santolucito** [comment]
It looks like integration with the info Matt posted on slack should be able to be done with this library: https://ruby-doc.org/stdlib-2.3.1/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-Basic+Authentication.

I think the code location we need to edit is here: https://github.com/newhaven-helpwithcovid/covid-volunteers/blob/e83bf38091fcd4738a38336d67db38c21b476556/app/views/devise/registrations/show.html.erb#L70

**Comment by santolucito** [comment]
@joyceduan07 I've assigned you for now - lmk if you don't want to do it or want to pull someone else in
