### ISSUE TITLE
Email "Administrator" upon new posting

### ISSUE THREAD

**Issue by tiffanywschan** [newhaven-helpwithcovid/covid-volunteers#56]
Is there a way to have some kind of mechanism in which job posts are not instantaneously posted but have to be approved by an administrator? We got our first spam post today.

**Comment by santolucito** [comment]
I would rather have an email alert be sent to admins when a new project is created. This allow project creators to see their project posted immediately, but also allows us to quickly filter spam. @chena11356 or @whonore  I think you guys know how the email alerts are working currently. Is this reasonable from the implementation side?

**Comment by santolucito** [comment]
emails to posters are working - we just need copy that code for sending an email
