### ISSUE TITLE
[Urgent] Include this text in pop-up for training status

### ISSUE THREAD

**Issue by tiffanywschan** [newhaven-helpwithcovid/covid-volunteers#62]
NewHavenHelpWithCovid.com has partnered with the training platform Blank Slate to provide a simple way for volunteers to quickly get up to speed on how to have the highest impact possible in your work, especially in light of frequently changing guidelines and best practices connected to COVID-19.

To protect our volunteers and others you work with during this pandemic, we ask all our volunteers who’ve marked their current location as “on-site in New Haven” to use Blank Slate to receive training on City of New Haven’s latest volunteer safety guidelines, which will only take 2-3 minutes. After that, depending on what you need to learn for your volunteer work, Blank Slate will send one or two nudges per week to make sure these updates stay front of mind. Your training status will be indicated on your volunteer profile so that our local partners can recruit with peace of mind.  

If you haven’t received an email from Blank Slate with a link to set up your account, please contact newhavenpandemic@gmail.com.

**Comment by sarimabbas** [comment]
Would it be OK if the "What's this?" text linked to the page created for https://github.com/newhaven-helpwithcovid/covid-volunteers/issues/63 in order to avoid redudancy? However, the pop-up is a nicer user experience, so I'm impartial

**Comment by tiffanywschan** [comment]
I agree that the popup offers a nice user experience. Let’s have that. Thanks!
