### ISSUE TITLE
[URGENT] Add blank slate to sign up workflow

### ISSUE THREAD

**Issue by santolucito** [newhaven-helpwithcovid/covid-volunteers#65]
Once we have the signup link from Matt, we need to either

show this link during signup with a message
or
redirect to that link (more intrusive, probably higher signup rate)

Any thoughts on which we would prefer?

**Comment by joyceduan** [comment]
Do you mean redirect to the link after they save their profile? I think redirection is a good idea. Even though it's intrusive I think if we stress the importance of it enough people will do it and will be less likely to forget about it

**Comment by tiffanywschan** [comment]
Okay, here's the plan: @santolucito @joyceduan07 @sarimabbas @whonore @chena11356 Not on the sign up page, but on the volunteer profile page that people have to create **after** signing up for an account, please add this one line right under the Training Status: To protect our volunteers and others you work with during this pandemic, we ask all our volunteers who’ve marked their current location as “on-site in New Haven” to to receive training on City of New Haven’s latest volunteer safety guidelines using a free learning app Blank Slate, which will only take 2-3 minutes. After you've done so, your training status will have a green check mark. Please use the following link to sign up for a free Blank Slate account using the same email address you used for this platform: https://app.blankslatetechnologies.com/app/index.html#/signUp?app=covid19. For more information, click "What is this?".
