### ISSUE TITLE
[URGENT] Please troubleshoot problems with making removed postings invisible while keeping all information of removed postings in database

### ISSUE THREAD

**Issue by tiffanywschan** [newhaven-helpwithcovid/covid-volunteers#70]

**Comment by santolucito** [comment]
I think this might be that we need a change in the controller for projects to only select the visible ones? I will dig into later this week, unless @chena11356 has a chance before then

**Comment by chena11356** [comment]
Removing postings seems to work on my end -- are you still experiencing problems with it?

**Comment by tiffanywschan** [comment]
Oh wow! It worked. At least the remove posting part. Thank you!

**Comment by tiffanywschan** [comment]
whoops, celebrated too early, it's still not working...

**Comment by chena11356** [comment]
Hmm are you using tiffany.chan@yale.edu? Since I set it so that admins can still see removed postings (didn't yet implement a way to mark which ones are removed), but others can't.

**Comment by tiffanywschan** [comment]
I signed out of my account but can still see the posting I removed while being an admin :(
