### ISSUE TITLE
add ssl cert

### ISSUE THREAD

**Issue by santolucito** [newhaven-helpwithcovid/covid-volunteers#76]
need to do this through our dns

**Comment by tiffanywschan** [comment]
@santolucito Our UConn partners are saying that the link is broken when they try to visit our site. I actually run into that problem every day from time to time. I solve it by refreshing my browser. But can we fix this? Thanks!

**Comment by santolucito** [comment]
is there any more information on what "broken" means?

**Comment by tiffanywschan** [comment]
No, but next time I encounter this problem, I'll make sure to screenshoot it.
