### ISSUE TITLE
Build analytics view

### ISSUE THREAD

**Issue by santolucito** [newhaven-helpwithcovid/covid-volunteers#78]
make a SQL query to get key stats/information

**Comment by tiffanywschan** [comment]
Inquiries of database:
For all positions ever posted on platform:
1) User ID, name, email address, and training status of volunteers who volunteer for a given position (display position title, name of organization, user ID who posted the position, email address of user who posted the position, date it was posted, date that a volunteer volunteered)
2) User ID, name, and email address of volunteers who are recruited for a given position (information from the remove posting form)  (display position title, name of organization, user ID who posted the position, email address of user who posted the position, date it was posted, date it was removed)

**Comment by tiffanywschan** [comment]
![](https://files.slack.com/files-pri/TMJ8WAV6E-F012C8J4PUM/img_20200423_093628__1_.jpg)

**Comment by santolucito** [comment]
@santolucito needs to send @sindhri  a dump of the db
