### ISSUE TITLE
Update project creation form

### ISSUE THREAD

**Issue by santolucito** [newhaven-helpwithcovid/covid-volunteers#88]
@tiffanywschan and @chloefink , can you chime in here on what exactly we would like changed?

**Comment by tiffanywschan** [comment]
Create new volunteer position
This information will be displayed publicly. Please follow the guidelines below to ensure efficient volunteer recruitment. If you have any questions about creating a position on this platform, please contact newhavenpandemic@gmail.com. 

Volunteer position title name* (if your organization is looking to fill positions with different responsibilities, please post each position separately) 
Organization*
Mission of organization*
Are you a registered organization? Yes/No*
Describe the volunteer position* (E.g. What are volunteers in this position expected to do? How many hours are approximately required per week? If the position is in-person, would PPE be provided? If you have your own application portal/Google form, please provide the URL here.) 
Skills needed
Project type*
Number of volunteers needed*
Level of exposure*
Background screening required*
Location*: Greater New Haven (on-site) / Remote (remove other Connecticut locales) 
Start date*
End date* (can enter a date or choose option: recurring) 
Compensation (optional)
Best way to get in touch (optional) 

Please remember to take down this  position posting when you have found the volunteers you need. 

* are fields that are required
