### ISSUE TITLE
Update volunteer profile page

### ISSUE THREAD

**Issue by tiffanywschan** [newhaven-helpwithcovid/covid-volunteers#89]
For affiliation, provide drop-down menu of Yale University, Quinnipiac University, Southern Connecticut State University, University of New Haven, Gateway Community College, Others (make this a mandatory field)

If you selected a university, please specify the school or college you are affiliated with. If you selected others, please specify the organization you are affiliated with. (make this a mandatory field)

Your location: Greater New Haven (on-site), Other Connecticut locales, Outside of Connecticut

**Comment by santolucito** [comment]
or a plaintext field that is mandatory and asks for affiliation/organization/employer? Maybe also specify that users and write "none" if they are unemployed? Im not sure about the best approach here

**Comment by tiffanywschan** [comment]
Yeah, I agree with plain text field that is mandatory and asks for Affiliation/Organization with the hint (write N/A if none) (employer usually rings alarm bells)
