### ISSUE TITLE
remove/redirect discord

### ISSUE THREAD

**Issue by santolucito** [newhaven-helpwithcovid/covid-volunteers#9]
There are a few places that direct users to the discord channel. `git grep 'discord'`. I think we have three options:

1) We can remove these
2) We can redirect to a new discord
3) We can redirect to the existing discord and create a new haven specific channel there

Thoughts?

**Comment by chena11356** [comment]
I've hidden references to Discord, but not removed entirely, just in case we want to integrate with HWC in the future
