### ISSUE TITLE
Add Chloe Fink on About page

### ISSUE THREAD

**Issue by tiffanywschan** [newhaven-helpwithcovid/covid-volunteers#90]
Please remove Kathleen Keefe from About page. Please add Chloe Fink on About page as Team Deputy.

**Comment by santolucito** [comment]
add flaurencya and lance as well

**Comment by tiffanywschan** [comment]
And remove Kathleen and Devin (Devin is more on the City Help With Covid)

**Comment by tiffanywschan** [comment]
Actually, don’t remove Devin.
