### ISSUE TITLE
layout issue with cards

### ISSUE THREAD

**Issue by santolucito** [newhaven-helpwithcovid/covid-volunteers#97]
Some SVGs are missing on prod, but are working fine on dev. I think it has something to do with this line. Perhaps something with the way assets are precompiled on prod is wrong? I don't understand this 100%

https://github.com/newhaven-helpwithcovid/covid-volunteers/blob/f4714cb83dc187a539da62acee8e9fb3abf9b6ce/config/environments/production.rb#L27

**Comment by santolucito** [comment]
Looking for help from anyone - maybe @joyceduan07 or @whonore

**Comment by whonore** [comment]
Fixed by running `rm -rf public/packs/ tmp/cache/; ./bin/webpack; RAILS_ENV=production rake assets:precompile` and restarting.
